### ISSUE TITLE
Filter in Workday should also apply on Table

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/HR-Addon#19]
![image](https://user-images.githubusercontent.com/22279621/168546129-80fe3bb4-df5a-459d-92e1-3818a153fe36.png)

The filter Employee and Date should also apply on the table to make sure, that entries from other employees or dates are not linked by mistake.

**Comment by estackhub** [comment]
This is the "Behaviour" by default.
If it isn't, you can recreate the error and post here

**Comment by wojosc** [comment]
![image](https://user-images.githubusercontent.com/22279621/169236478-53da0ff9-389d-4a20-bbc3-d6d4dc0849e1.png)
