### ISSUE TITLE
Create DocType "Weekly Working Hours"

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/HR-Addon#2]
Please create a doctype "Weekly Working Hours" in this we can hold information about the work week of an employee in a certain time period (for example 01.01.2022-31.12.2022). Here we can set an number of hours that an employee should work per day. We will have a field for each day (monday, tuesday, wednesday, thursday, friday, saturday, sunday). In these fields we can put in an amount of hours. These will reflect the target hours of an employee for a certain day.
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/22279621/166693215-d13bdfd1-7fd3-43a8-921d-07c6e782a838.png">

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/22279621/166693271-e0c61c16-c639-4180-9bc2-8c381b7cc1bf.png">

**Comment by estackhub** [comment]
Weekly Working Hours doctype created, more work needed to be done on name and total

**Comment by wojosc** [comment]
@estackhub whats the benefit of going for a table here? 
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/22279621/166890798-770b99d2-9b22-41ea-afa3-eb016ae9ace8.png">

**Comment by wojosc** [comment]
Table used as it's similar to erpnext standard (Assignment Rules)
