### ISSUE TITLE
hr module is separate app

### ISSUE THREAD

**Issue by knudeh** [phamos-eu/HR-Addon#21]
Since hr module moved to its own app, one has to adjust an import statement.
hr_addon/hr_addon/doctype/workday/workday.py

- from erpnext.hr.utils import get_holiday_dates_for_employee, validate_active_employee
+ from hrms.hr.utils import get_holiday_dates_for_employee, validate_active_employee

**Comment by roquegv** [comment]
Is this issue still applicable? 

I don't see those lines in that files :thinking:

**Comment by roquegv** [comment]
This seems to be solved by this commit https://github.com/phamos-eu/HR-Addon/commit/01f4e81a966447df03496ab1b0dbe0d4f9dd840a
