### ISSUE TITLE
Create DocType "Workday"

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/HR-Addon#3]
The Workday works similar to Attendance and will show us the information about the work time of an employee for a certain day.

This is an add-on to erpnexts original Attendance function and will getch information about the attendance and about Employee Checkin without making a dependency between the two.
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/22279621/166693689-b85c6c05-01c0-449b-82a6-92eac4dc504d.png">

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/22279621/166693740-e44abd7f-81c4-44a3-b0b1-5b20aef8dd73.png">

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/22279621/166693786-e7150d4a-9ef1-42f8-9622-97900d03be71.png">

**Comment by estackhub** [comment]
Workday Doctype is in beta and ready for testing.
Rolling out other updates in coming days.

**Comment by wojosc** [comment]
@estackhub thanks. I have had a first look. Here are my comments:

- [ ] Employee Checkin should be pulled from combination employee+date reason is, that there are cases, where an employee is on leave and will still come. In these cases Employee Checkin will not be linked to Attendance but still be needed to create the final report

Best

**Comment by estackhub** [comment]
@wojosc adding 'date' feature will be included the next update

**Comment by estackhub** [comment]
@wojosc  "Employee Checkin should be pulled from combination employee+date" now ready for testing

**Comment by wojosc** [comment]
Employee Checkins should also be fetched when there is no Attendance linked. For now this is of minor importance. I will create a new issue for that and close this one for now.
