### ISSUE TITLE
Create Function for processing work days

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/HR-Addon#4]
In the work day List we could have a button with a function opening a wizard to process all work days

![image](https://user-images.githubusercontent.com/22279621/166694144-3b337049-1860-486d-bae8-ce9db17476db.png)

This could follow the original design of erpnext when processing Attendance in the Attendance List
![image](https://user-images.githubusercontent.com/22279621/166694457-39fb2e09-028a-4f5e-ace8-8e6330594f45.png)

**Comment by wojosc** [comment]
![image](https://user-images.githubusercontent.com/22279621/166695436-c37721f4-89c7-45dd-9c8a-2c799b21bc3b.png)

**Comment by wojosc** [comment]
<img width="669" alt="image" src="https://user-images.githubusercontent.com/22279621/166695527-0f3abe58-ce3c-49c4-b571-1eded4c85e6f.png">

**Comment by wojosc** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/22279621/167670684-ef5e4666-9090-4d02-a373-6490beb956c4.png">

Processing Workday will probalby only need a
Link Field to Employee
A "From Date" datepicker
A "To Date" datepicker

And a button to trigger the function.

Result should be:
Records for Workday for the Employee and Time-Range given should be created in bulk with the table "Emplyoee Checkins" filled and the attendance fetched (if any, if not leave blank) for the given date

**Comment by estackhub** [comment]
https://user-images.githubusercontent.com/85407202/167912754-009c3835-9240-450c-8b9f-8c4196393152.mp4

I had to go the monthly way so user could get a feedback while trying to process the workday

**Comment by estackhub** [comment]
The function that does the bulk processing of workday and  pulling the checkins with it, will be ready for testing in coming days

**Comment by estackhub** [comment]
> The function that does the bulk processing of workday and pulling the checkins with it, will be ready for testing in coming days

Updated

**Comment by wojosc** [comment]
The process triggered by the button should create a entry Workday for each Employee and date no matter if there are Employee Checkins for this date or not. Also is should not matter if there is an Attendance for that day or not.

Having all days for each employee allows us to create a custom Report via the Report Builder to see which dates need handling and maybe some refreshes to be done.

If there is a Attendance of any kind this should be pulled. If there is not, the entry Workday should still be created.

**Comment by PawanMeh** [comment]
For the issue related to workday(s) not created when there are no attendance logs, maybe an else condition should be added for the if condition [here]( https://github.com/phamos-eu/HR-Addon/blob/master/hr_addon/hr_addon/doctype/workday/workday.py#L34).

In the else, something similar to the code at lines 42 to 52 can be done.
