### ISSUE TITLE
No break hours if target hours is less than 6 hours

### ISSUE THREAD

**Issue by roquegv** [phamos-eu/HR-Addon#41]
New request from the customer:
Is it possible to set a general switch that all working hours below 6 hours do not include breaks? Could this perhaps be stored in the weekly working hours for each employee?
Actually, almost all cases of this kind are already covered (illness, vacation, work on days without working hours.) Only if you use overtime to shorten your working time, it can become a problem.
In German labor law, if you work less than 6 hours, you don't have to take a break. Unfortunately, this cannot be deactivated in general. Certain conditions require that the employee remains available or is still in the company until a certain time. (Telephone availability...) Besides, Germany is not the only country.
So could you add the option that you can activate at one point that all or one employee has no break if they work under 6 hours? How complex is this?
For me weekly working order would be the best place to switch this option on and off individually.

Tasks:
- [ ] Add a "No break hours if target hours is less than 6 hours" checkbox field in Weekly Working Hours
- [ ] Add function to process this condition

**Comment by wojosc** [comment]
@roquegv please update your checkboxes in this issue. Marcus has approved the changes and was able to replicate his needs at a satisfactory level. Thank you.
