### ISSUE TITLE
Create new "View Attendance" Report

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/HR-Addon#5]
All data needed inside of the "View Attendance" Report will now be available in the DocType Workday

![image](https://user-images.githubusercontent.com/22279621/166697162-ec287cfd-552b-4540-bf4e-5d5aa2295228.png)

Still we will need to create a report in which we have nice filters to be able zu quickly get a monthly overview of an employee

**Comment by beingeek** [comment]
Is this report TODO was about 'Work Hour Report' ?
![image](https://github.com/user-attachments/assets/cb7c2acc-50f8-4e0a-b720-caae75991cd1)
@wojosc @reggaetuna
