### ISSUE TITLE
App Description and Work to be done

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/HR-Addon#6]
General
All data witch is connected to time should be in a time format hh:mm:ss

List of Tasks
- [x] Create Custom App
- [x] Create DocType Weekly Working Hours
- [x] Create DocType Workday
- [ ] Create Report

**Comment by beingeek** [comment]
Is this report TODO was about 'Work Hour Report' ?
![image](https://github.com/user-attachments/assets/cb7c2acc-50f8-4e0a-b720-caae75991cd1)
@wojosc @reggaetuna
