### ISSUE TITLE
Changable ICS folder

### ISSUE THREAD

**Issue by roquegv** [phamos-eu/HR-Addon#67]
from @marcus-wiegand 

> Customer requirement:
> The ICS file should be generated in the following folder, so that it can be accessed by OwnCloud and stays behind a password barrier.
> Please store the calendar.ics in this location on the x22 (ERPnext server from Customer): /home/pdW9PwKp/owncloud/calendar/
> 
> Implementation suggestion:
> The link should be able to be customized here in the best case:
> System Path /app/hr-addon-settings
> (HR Addon Settings)
> Then every user without programming experience can always adjust the path.
> But there might be a security request from the server. I cannot estimate that at the moment.
> 
> Under the corresponding Field should be a small explanation, how to enter the path generally.  

TODO:
- Add a "ICS folder path" field in HR Addon Settings
- Store the ICS file in that folder

**Comment by wojosc** [comment]
@roquegv @marcus-wiegand I have edited the last comment and removed the clear customer URL. Please make sure not to use customer Server URLs in public repos. In fact try your best to avoid having to use such URLs on any open channels. Thank you.

**Comment by roquegv** [comment]
@wojosc noticed :ok_hand:

**Comment by roquegv** [comment]
Closing because the PR is merged
