### ISSUE TITLE
Workday - add addtional information

### ISSUE THREAD

**Issue by ReachyBayern** [phamos-eu/HR-Addon#84]
**current problems:**
- breaks are not calculated correct if there are more then 2 checkins per employee. 07:00 - 12:00 and 14:00 - 17:00. Currently the working day also deducts the entire break of the weekly working hours configuration, even though the employee has taken a break with checkins/out
- breaks for working hours >9h could not be calculated (German law, 6h--> 30 minutes, 9h --> 45minutes)
- compensation off is taking target hours from weekly working hours. To have the correct hours it is neccessary to have no target hours there.
- count of breaks will not be filled

**Proposal:**

- add leave type, fetched from attendance to have this information direkt in the report.
- calculation breaks by recognizing real breaks by employe (more then 2 checkins a day). solved at the moment for us by a server script 
- client script to field update fo total_target_seconds, if the targe hours were changed manually. solved at the moment by client script
- 9h - additional break
   - enhanced weekly working hours
      - checkbox using 9h break
      - float field for break time for 9h
    - enhance the break calculation recognizing the 9h. solved at the moment for us by a server script
- add checkbox in leave_type by customization to set if target hours should be taken and take in the calculation logik. 

server-scripts and client scripts could be sent as example if this is usefull.

**Comment by wojosc** [comment]
thanks you for sharing this. Yes, please also add the scripts as they will be helpful.

@reggaetuna please go over this list and give feedback to what might already be part of the app and just needs understanding/clarification through documentation, what might be worked on in the develop branch already.

Thanks

**Comment by ReachyBayern** [comment]
client script workday - fieldupdate (target_hours)

```
frappe.ui.form.on('Workday', {
    target_hours: function(frm, cdt, cdn) {
        console.log('setting total_target_second.....s');
        frappe.model.set_value(cdt, cdn, 'total_target_seconds', frappe.model.get_value(cdt, cdn, 'target_hours')*3600);
        
    }
});
```

**Comment by ReachyBayern** [comment]
server script workday - before save: to calculate breaks for hours >9 and multiple checkins

l_exp_break_hours         = float(doc.expected_break_hours)
l_hours_worked            = float(doc.hours_worked)
l_set_break_time_after_9h = doc.custom_set_break_time_after_9h
l_break_time_after_9_h    = doc.custom_break_time_after_9h
if (l_hours_worked >= 9 and l_exp_break_hours < 0.75 and l_set_break_time_after_9h ):
        l_exp_break_hours = 0.75
        doc.expected_break_hours = 0.75
l_break_count = (len(doc.employee_checkins) * 0.5 ) - 1
if (l_break_count >= 0):
    l_break_hours = float(doc.break_hours)
    l_new_break_seconds = (l_exp_break_hours - l_break_hours) * 3600
    if (l_new_break_seconds <= 0):
        l_new_break_seconds = 0
    l_new_working_hours = l_hours_worked - (l_new_break_seconds / 3600 )
    doc.actual_working_hours = l_new_working_hours
    doc.total_break_seconds  = l_new_break_seconds
    doc.number_of_breaks     = l_break_count
else:
    doc.number_of_breaks = 0

**Comment by beingeek** [comment]
version-14 and version-15 is updated and issue resolved
