### ISSUE TITLE
Creating Work Days - canceled attendance is taken instead of current attendance

### ISSUE THREAD

**Issue by ReachyBayern** [phamos-eu/HR-Addon#91]
If a leave application was canceled, changed and again executed as a new leave application record, the worng record will be found during creation of work days because in the sql statement the "docstatus" filter is missing. The solution should look like:

File: Root / opt / bench / erpnext / apps / hr_addon / hr_addon / hr_addon / api / utils.py

Function: 
```
def get_employee_attendance(employee,atime):
    ''' select DATE('date time');'''
    employee = employee
    atime = atime
    
    #checkin_list = []
    attendance_list = frappe.db.sql(
        """
        SELECT  name,employee,status,attendance_date,shift FROM `tabAttendance` 
        WHERE employee='%s' AND DATE(attendance_date)= DATE('%s') AND docstatus < 2 ORDER BY attendance_date ASC
        """%(employee,atime), as_dict=1
    )
    #print(f'\n\n\n\n inside valid : {checkin_list} \n\n\n\n')
    return attendance_list
```

**Comment by wojosc** [comment]
@reggaetuna @beingeek

**Comment by beingeek** [comment]
checking

**Comment by beingeek** [comment]
resolved in version-14 and version-15 via following PR's
#104 [version-14](https://github.com/phamos-eu/HR-Addon/blob/6edb8c146a0fc95dcbe188fbb530365ebbde55e2/hr_addon/hr_addon/api/utils.py#L326)
#102  [version-15](https://github.com/phamos-eu/HR-Addon/blob/6edb8c146a0fc95dcbe188fbb530365ebbde55e2/hr_addon/hr_addon/api/utils.py#L326)
